;TO COUNT THE NUMBER OF 1'S AND 0'S IN THE GIVEN 16BIT NUMBER
;INORDER TO KEEP THE PROGRAM SIMPLE, WE ARE CONSIDERING NUMBER OF 1'S AND 0'S LESS THAN 16
ASSUME CS:CODE, DS:DATA

DATA SEGMENT
    MSG1 DB 0AH,0DH,"ENTER DIGIT :$"
    MSG2 DB 0AH,0DH,"NUMBER OF 1'S :$"
    MSG3 DB 0AH,0DH,"NUMBER OF 0'S :$"
    NUMBUFFER DB 5 DUP('$')
DATA ENDS

CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX
    MOV CX,0004H
    MOV BX,1010H
    CLC
INPUT:    LEA DX,MSG1 ;1ST DIGIT
    MOV AH,09H
    INT 21H
    MOV AH,01H
    INT 21H
    CMP AL,'A'
    JB DIGIT
    SUB AL,07H
DIGIT:SUB AL,30H
    MOV DL,04H
 ROT:RCR AL,1 ; ROTATE RIGHT4 TIMES TO GET THE BITS
    JNC COUNT
    DEC BX
COUNT:DEC DL
    JNZ ROT
    LOOP INPUT

    LEA DX, MSG2
    MOV AH, 09H
    INT 21H  
    SUB BH,BL
    MOV CX, 3030H
    MOV CX,10
DIGIT1:XOR AX, AX
    MOV AL, BH
    DIV CL
    ADD AL,'0'
    MOV [NUMBUFFER],AL
    MOV DL,AH
    ADD DL,'0'
    MOV [NUMBUFFER+1],DL
    LEA DX,NUMBUFFER
    MOV AH,09H
    INT 21H     ; Display 1'S

    LEA DX, MSG3
    MOV AH, 09H
    INT 21H  

DIGIT0:XOR AX, AX
    MOV AL, BL
    DIV CL
    ADD AL,'0'
    MOV [NUMBUFFER],AL
    MOV DL,AH
    ADD DL,'0'
    MOV [NUMBUFFER+1],DL
    LEA DX,NUMBUFFER
    MOV AH,09H
    INT 21H   ;DISPLAY 0'S

    MOV AH, 4CH
    INT 21H
CODE ENDS
END START

